blank_issues_enabled: false
contact_links:
    - name: Enhancecord Support Server
      url: https://discord.gg/5Xh2W87egW
      about: If you need help regarding Enhancebop or Enhancecord, please join our support server!
